'use client';

import { AlertTriangle, CheckCircle2, ExternalLink, FilePlus2, FileStack, Link2, MoreHorizontal, Plus, Search, Trash2, Upload, X } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react';
import { EmptyState } from '@/components/empty-state';
import { PageHeader } from '@/components/page-header';
import { loadResearchMaterials } from '@/lib/supabase/queries';
import { deleteResearchMaterial, MAX_MATERIAL_SIZE, researchMaterialUrl, submitResearchMaterial } from '@/lib/supabase/materials';
import type { ResearchMaterial } from '@/types/study';

const typeOptions=[
  ['pdf','PDF'],['spreadsheet','Excel / planilha'],['csv','CSV'],['document','Word / documento'],
  ['presentation','PowerPoint / apresentação'],['image','Imagem'],['zip','ZIP'],['other','Outro documento'],
] as const;

export function MaterialsPage() {
  const [open,setOpen]=useState(false);const [query,setQuery]=useState('');const [typeFilter,setTypeFilter]=useState('');const [materials,setMaterials]=useState<ResearchMaterial[]>([]);
  const [loading,setLoading]=useState(true);const [toast,setToast]=useState<{kind:'success'|'error';message:string}|null>(null);const [deleteTarget,setDeleteTarget]=useState<ResearchMaterial|null>(null);const [deleting,setDeleting]=useState(false);
  useEffect(()=>{loadResearchMaterials().then(setMaterials).catch(()=>setMaterials([])).finally(()=>setLoading(false));},[]);
  const filtered=useMemo(()=>materials.filter((item)=>(!typeFilter||item.material_type===typeFilter)&&`${item.title} ${item.description??''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))),[materials,query,typeFilter]);
  const showToast=(kind:'success'|'error',message:string)=>{setToast({kind,message});setTimeout(()=>setToast(null),6000);};
  const onCreated=(material:ResearchMaterial)=>{setMaterials((current)=>[material,...current]);setOpen(false);showToast('success',`“${material.title}” foi adicionado à biblioteca.`);};
  const confirmDelete=async()=>{if(!deleteTarget)return;setDeleting(true);try{await deleteResearchMaterial(deleteTarget);setMaterials((current)=>current.filter((item)=>item.id!==deleteTarget.id));showToast('success','Material excluído.');setDeleteTarget(null);}catch(error){console.error('Falha ao excluir material.',error);showToast('error','Não foi possível excluir o material.');}finally{setDeleting(false);}};
  return <section className="animate-in p-4 sm:p-6 lg:p-8"><PageHeader eyebrow="Biblioteca da pesquisa" title="Materiais" description="Centralize documentos, bases, referências e links utilizados ao longo do estudo." actions={<button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#176b52] px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[#125b45]"><Plus size={16}/>Adicionar material</button>}/>
    <div className="mb-4 rounded-2xl border border-[#cfe1d8] bg-[#edf6f1] p-4 text-xs leading-5 text-[#315f4f]"><strong>Acesso temporariamente aberto:</strong> participantes com o link podem adicionar e excluir materiais sem login. Arquivos têm limite de 25 MB; edição e sobrescrita continuam bloqueadas.</div>
    {toast&&<div role={toast.kind==='error'?'alert':'status'} className={`mb-4 flex items-center gap-2 rounded-xl border p-3 text-xs font-medium ${toast.kind==='success'?'border-emerald-200 bg-emerald-50 text-emerald-800':'border-red-200 bg-red-50 text-red-800'}`}>{toast.kind==='success'?<CheckCircle2 size={16}/>:<AlertTriangle size={16}/>} {toast.message}</div>}
    <div className="flex flex-col gap-3 rounded-2xl border border-[#dce4df] bg-white p-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl bg-[#f4f6f4] px-3"><Search size={15} className="text-[#81908a]"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Buscar por título ou descrição" className="h-10 w-full bg-transparent text-xs outline-none"/></label><select aria-label="Filtrar por tipo" value={typeFilter} onChange={(event)=>setTypeFilter(event.target.value)} className="rounded-xl border border-[#dce4df] bg-white px-3 text-xs font-medium text-[#58645f]"><option value="">Todos os tipos</option>{typeOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}<option value="link">URL / link</option></select></div>
    <div className="mt-4">{filtered.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item)=><MaterialCard key={item.id} material={item} onDelete={()=>setDeleteTarget(item)}/>)}</div>:<EmptyState icon={FileStack} title={loading?'Carregando materiais…':query||typeFilter?'Nenhum material encontrado':'Sua biblioteca começa aqui'} description={loading?'Consultando a biblioteca pública.':query||typeFilter?'Tente outro termo ou ajuste o filtro.':'Adicione arquivos, links e referências para manter as fontes da pesquisa organizadas.'} action={!loading&&!query&&!typeFilter?<button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 text-xs font-semibold text-[#176b52]"><FilePlus2 size={14}/>Cadastrar primeiro material</button>:undefined}/>}</div>
    {open&&<MaterialForm onClose={()=>setOpen(false)} onCreated={onCreated}/>} {deleteTarget&&<DeleteConfirmation material={deleteTarget} deleting={deleting} onCancel={()=>!deleting&&setDeleteTarget(null)} onConfirm={confirmDelete}/>}<style>{`.field{width:100%;border:1px solid #dce4df;border-radius:12px;background:#fafbfa;padding:0 12px;height:42px;font-size:12px;outline:none}.field:focus{border-color:#6f9c8c;box-shadow:0 0 0 3px #e4efe9}`}</style>
  </section>;
}

function MaterialCard({material,onDelete}:{material:ResearchMaterial;onDelete:()=>void}){
  const url=researchMaterialUrl(material);const date=material.publication_date??material.created_at;
  return <article className="rounded-[20px] border border-[#dce4df] bg-white p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f0eb] text-[#176b52]"><FileStack size={18}/></span><div className="flex items-center gap-1"><span className="rounded-full bg-[#f0f3f1] px-2 py-1 text-[10px] font-semibold uppercase text-[#66736e]">{friendlyType(material.material_type)}</span><button onClick={onDelete} title="Excluir material" aria-label={`Excluir ${material.title}`} className="grid h-7 w-7 place-items-center rounded-lg text-[#8a9490] hover:bg-red-50 hover:text-red-700"><MoreHorizontal size={16}/></button></div></div><h3 className="mt-4 text-sm font-semibold">{material.title}</h3><p className="mt-1 line-clamp-3 text-xs leading-5 text-[#74807b]">{material.description??'Sem descrição.'}</p><div className="mt-3 text-[10px] leading-4 text-[#909a95]">{material.uploader_name&&<p>Colaboração: {material.uploader_name}</p>}{material.file_size_bytes&&<p>Tamanho: {formatFileSize(material.file_size_bytes)}</p>}<p>{new Date(date).toLocaleDateString('pt-BR',{timeZone:'UTC'})}</p></div>{url&&<a href={url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-[#176b52]">Abrir material <ExternalLink size={13}/></a>}</article>;
}

function DeleteConfirmation({material,deleting,onCancel,onConfirm}:{material:ResearchMaterial;deleting:boolean;onCancel:()=>void;onConfirm:()=>void}){
  return <div className="fixed inset-0 z-[60] grid place-items-center bg-[#14201c]/45 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" aria-labelledby="delete-material-title" className="w-full max-w-md rounded-[22px] bg-white p-6 shadow-2xl"><span className="grid h-11 w-11 place-items-center rounded-xl bg-red-50 text-red-700"><Trash2 size={19}/></span><h2 id="delete-material-title" className="mt-4 text-lg font-semibold">Excluir este material?</h2><p className="mt-2 text-xs leading-5 text-[#68746f]">{material.storage_path?'O arquivo e o registro da biblioteca serão removidos. Esta ação não poderá ser desfeita.':'O registro da biblioteca será removido. Esta ação não poderá ser desfeita.'}</p><div className="mt-5 flex justify-end gap-2"><button disabled={deleting} onClick={onCancel} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-[#66726d]">Cancelar</button><button disabled={deleting} onClick={onConfirm} className="rounded-xl bg-red-700 px-4 py-2.5 text-xs font-semibold text-white disabled:bg-red-300">{deleting?'Excluindo…':'Excluir definitivamente'}</button></div></div></div>;
}

function MaterialForm({onClose,onCreated}:{onClose:()=>void;onCreated:(material:ResearchMaterial)=>void}){
  const [title,setTitle]=useState('');const [materialType,setMaterialType]=useState('pdf');const [publicationDate,setPublicationDate]=useState('');const [description,setDescription]=useState('');
  const [uploaderName,setUploaderName]=useState('');const [uploaderEmail,setUploaderEmail]=useState('');const [sourceMode,setSourceMode]=useState<'file'|'url'>('file');const [file,setFile]=useState<File|null>(null);const [externalUrl,setExternalUrl]=useState('');
  const [honeypot,setHoneypot]=useState('');const [submitting,setSubmitting]=useState(false);const [error,setError]=useState<string|null>(null);
  const submit=async(event:FormEvent)=>{event.preventDefault();setError(null);const previous=Number(localStorage.getItem('geometro-last-material-submit')??0);if(Date.now()-previous<10000){setError('Aguarde alguns segundos antes de enviar outro material.');return;}setSubmitting(true);try{const material=await submitResearchMaterial({title,description,materialType,publicationDate,uploaderName,uploaderEmail,file:sourceMode==='file'?file:null,externalUrl:sourceMode==='url'?externalUrl:'',honeypot});localStorage.setItem('geometro-last-material-submit',String(Date.now()));onCreated(material);}catch(nextError){setError(nextError instanceof Error?nextError.message:'Não foi possível salvar o material.');}finally{setSubmitting(false);}};
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#14201c]/45 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-[22px] bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold tracking-[-.025em]">Novo material</h2><p className="mt-1 text-xs text-[#77827e]">Envio sem login para participantes com acesso ao link.</p></div><button onClick={onClose} className="rounded-lg p-2 text-[#76827d] hover:bg-[#eef2ef]" aria-label="Fechar"><X size={17}/></button></div>
    <form className="mt-5 space-y-4" onSubmit={submit}><input value={honeypot} onChange={(event)=>setHoneypot(event.target.value)} name="website" tabIndex={-1} autoComplete="off" className="hidden" aria-hidden="true"/>
      <Field label="Título *"><input required maxLength={200} value={title} onChange={(event)=>setTitle(event.target.value)} placeholder="Ex.: Nota técnica sobre mobilidade" className="field"/></Field>
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><select value={sourceMode==='url'?'link':materialType} disabled={sourceMode==='url'} onChange={(event)=>setMaterialType(event.target.value)} className="field">{typeOptions.map(([value,label])=><option key={value} value={value}>{label}</option>)}{sourceMode==='url'&&<option value="link">URL / link</option>}</select></Field><Field label="Data de publicação"><input type="date" value={publicationDate} onChange={(event)=>setPublicationDate(event.target.value)} className="field"/></Field></div>
      <Field label="Descrição"><textarea rows={3} maxLength={4000} value={description} onChange={(event)=>setDescription(event.target.value)} placeholder="Contexto e relevância do material" className="field min-h-24 py-3"/></Field>
      <div className="grid gap-3 sm:grid-cols-2"><button type="button" onClick={()=>{setSourceMode('file');setExternalUrl('');}} className={`flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl border border-dashed text-xs font-medium ${sourceMode==='file'?'border-[#5c977f] bg-[#edf6f1] text-[#176b52]':'border-[#cdd8d2] bg-[#f8faf8] text-[#65716c]'}`}><Upload size={18}/>Anexar arquivo</button><button type="button" onClick={()=>{setSourceMode('url');setFile(null);}} className={`flex min-h-20 flex-col items-center justify-center gap-2 rounded-xl border border-dashed text-xs font-medium ${sourceMode==='url'?'border-[#5c977f] bg-[#edf6f1] text-[#176b52]':'border-[#cdd8d2] bg-[#f8faf8] text-[#65716c]'}`}><Link2 size={18}/>Cadastrar URL</button></div>
      {sourceMode==='file'?<Field label="Arquivo *"><input required type="file" accept=".pdf,.xls,.xlsx,.csv,.doc,.docx,.ppt,.pptx,.png,.jpg,.jpeg,.webp,.gif,.zip,.txt,.rtf,.odt,.ods,.odp" onChange={(event)=>setFile(event.target.files?.[0]??null)} className="block w-full rounded-xl border border-[#dce4df] bg-[#fafbfa] p-2 text-xs file:mr-3 file:rounded-lg file:border-0 file:bg-[#e7f1eb] file:px-3 file:py-2 file:font-semibold file:text-[#176b52]"/><span className="mt-1 block text-[10px] text-[#8a9490]">PDF, Office, CSV, imagens, ZIP e documentos — máximo {(MAX_MATERIAL_SIZE/1024/1024).toLocaleString('pt-BR')} MB.</span></Field>:<Field label="URL *"><input required type="url" value={externalUrl} onChange={(event)=>setExternalUrl(event.target.value)} placeholder="https://…" className="field"/></Field>}
      <div className="grid gap-4 sm:grid-cols-2"><Field label="Seu nome"><input maxLength={120} value={uploaderName} onChange={(event)=>setUploaderName(event.target.value)} className="field" placeholder="Opcional"/></Field><Field label="E-mail"><input type="email" maxLength={254} value={uploaderEmail} onChange={(event)=>setUploaderEmail(event.target.value)} className="field" placeholder="Opcional e não exibido"/></Field></div>
      {error&&<p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-[11px] leading-5 text-red-800">{error}</p>}
      <div className="rounded-xl bg-[#f1f6f3] p-3 text-[11px] leading-5 text-[#557066]">O arquivo recebe um nome interno aleatório. Sobrescrita e edição permanecem bloqueadas; a exclusão exige confirmação explícita.</div>
      <div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-[#66726d]">Cancelar</button><button disabled={submitting} className="rounded-xl bg-[#176b52] px-4 py-2.5 text-xs font-semibold text-white disabled:bg-[#b8c8c1]">{submitting?'Salvando…':'Salvar material'}</button></div>
    </form></div></div>;
}

function Field({label,children}:{label:string;children:ReactNode}){return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-[#55615d]">{label}</span>{children}</label>;}
function friendlyType(type:string){return type==='spreadsheet'?'planilha':type==='presentation'?'apresentação':type==='document'?'documento':type==='link'?'link':type;}
function formatFileSize(bytes:number){return bytes>=1024*1024?`${(bytes/1024/1024).toLocaleString('pt-BR',{maximumFractionDigits:1})} MB`:`${Math.ceil(bytes/1024).toLocaleString('pt-BR')} KB`;}
