'use client';

import { ExternalLink, FilePlus2, FileStack, Link2, Plus, Search, Upload, X } from 'lucide-react';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { EmptyState } from '@/components/empty-state';
import { PageHeader } from '@/components/page-header';
import { loadResearchMaterials } from '@/lib/supabase/queries';
import type { ResearchMaterial } from '@/types/study';

export function MaterialsPage() {
  const [open,setOpen] = useState(false);
  const [query,setQuery] = useState('');
  const [materials,setMaterials] = useState<ResearchMaterial[]>([]);
  useEffect(()=>{ loadResearchMaterials().then(setMaterials).catch(()=>setMaterials([])); },[]);
  const filtered=useMemo(()=>materials.filter((item)=>`${item.title} ${item.description ?? ''}`.toLocaleLowerCase('pt-BR').includes(query.toLocaleLowerCase('pt-BR'))),[materials,query]);
  return <section className="animate-in p-4 sm:p-6 lg:p-8"><PageHeader eyebrow="Biblioteca da pesquisa" title="Materiais" description="Centralize documentos, bases, referências e links utilizados ao longo do estudo." actions={<button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-[#176b52] px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-[#125b45]"><Plus size={16}/>Adicionar material</button>}/>
    <div className="flex flex-col gap-3 rounded-2xl border border-[#dce4df] bg-white p-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 rounded-xl bg-[#f4f6f4] px-3"><Search size={15} className="text-[#81908a]"/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Buscar por título ou descrição" className="h-10 w-full bg-transparent text-xs outline-none"/></label><select aria-label="Filtrar por tipo" className="rounded-xl border border-[#dce4df] bg-white px-3 text-xs font-medium text-[#58645f]"><option>Todos os tipos</option><option>Documento</option><option>Planilha</option><option>Link ou artigo</option><option>Imagem</option></select><select aria-label="Filtrar por tag" className="rounded-xl border border-[#dce4df] bg-white px-3 text-xs font-medium text-[#58645f]"><option>Todas as tags</option></select></div>
    <div className="mt-4">{filtered.length?<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((item)=><article key={item.id} className="rounded-[20px] border border-[#dce4df] bg-white p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e8f0eb] text-[#176b52]"><FileStack size={18}/></span><span className="rounded-full bg-[#f0f3f1] px-2 py-1 text-[10px] font-semibold uppercase text-[#66736e]">{item.material_type.replaceAll('_',' ')}</span></div><h3 className="mt-4 text-sm font-semibold">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#74807b]">{item.description ?? 'Sem descrição.'}</p>{item.external_url&&<a href={item.external_url} target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-1.5 text-xs font-semibold text-[#176b52]">Abrir material <ExternalLink size={13}/></a>}</article>)}</div>:<EmptyState icon={FileStack} title={query?'Nenhum material encontrado':'Sua biblioteca começa aqui'} description={query?'Tente outro termo ou ajuste os filtros.':'Adicione arquivos, links e referências para manter as fontes da pesquisa organizadas e acessíveis.'} action={!query?<button onClick={()=>setOpen(true)} className="inline-flex items-center gap-2 text-xs font-semibold text-[#176b52]"><FilePlus2 size={14}/>Cadastrar primeiro material</button>:undefined}/>}</div>
    {open && <div className="fixed inset-0 z-50 grid place-items-center bg-[#14201c]/45 p-4 backdrop-blur-sm"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-[22px] bg-white p-5 shadow-2xl sm:p-6"><div className="flex items-start justify-between"><div><h2 className="text-lg font-semibold tracking-[-.025em]">Novo material</h2><p className="mt-1 text-xs text-[#77827e]">Registre uma fonte utilizada no estudo.</p></div><button onClick={()=>setOpen(false)} className="rounded-lg p-2 text-[#76827d] hover:bg-[#eef2ef]" aria-label="Fechar"><X size={17}/></button></div><form className="mt-5 space-y-4" onSubmit={(e)=>e.preventDefault()}><Field label="Título *"><input required placeholder="Ex.: Base de CEPs georreferenciados" className="field"/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><select className="field"><option>PDF</option><option>CSV</option><option>XLS/XLSX</option><option>DOC/DOCX</option><option>Imagem</option><option>Apresentação</option><option>ZIP</option><option>Link ou artigo</option><option>Google Docs/Sheets</option><option>Outro</option></select></Field><Field label="Data de publicação"><input type="date" className="field"/></Field></div><Field label="Descrição"><textarea rows={3} placeholder="Contexto e relevância do material" className="field py-3"/></Field><div className="grid gap-3 sm:grid-cols-2"><button type="button" className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-[#cdd8d2] bg-[#f8faf8] text-xs font-medium text-[#65716c]"><Upload size={18}/>Selecionar arquivo</button><button type="button" className="flex min-h-24 flex-col items-center justify-center gap-2 rounded-xl border border-dashed border-[#cdd8d2] bg-[#f8faf8] text-xs font-medium text-[#65716c]"><Link2 size={18}/>Adicionar URL</button></div><div className="rounded-xl bg-amber-50 p-3 text-[11px] leading-5 text-amber-800">O envio será habilitado quando as credenciais e as políticas de acesso do Supabase forem configuradas.</div><div className="flex justify-end gap-2 pt-2"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl px-4 py-2.5 text-xs font-semibold text-[#66726d]">Cancelar</button><button disabled className="cursor-not-allowed rounded-xl bg-[#b8c8c1] px-4 py-2.5 text-xs font-semibold text-white">Salvar material</button></div></form></div></div>}
    <style>{`.field{width:100%;border:1px solid #dce4df;border-radius:12px;background:#fafbfa;padding:0 12px;height:42px;font-size:12px;outline:none}.field:focus{border-color:#6f9c8c;box-shadow:0 0 0 3px #e4efe9}`}</style>
  </section>;
}

function Field({ label, children }:{ label:string; children:ReactNode }) { return <label className="block"><span className="mb-1.5 block text-[11px] font-semibold text-[#55615d]">{label}</span>{children}</label>; }
