import { AlertTriangle, BookOpenText, Clock3, Info } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import type { ReactNode } from 'react';

const sections:Array<{title:string;content:ReactNode}>=[
  {title:'Base original',content:<><p>A fonte documentada é o arquivo <code>dados_imoveis.xlsx</code>, organizado em planilhas anuais de 2011 a 2024 para Salvador/BA. A unidade disponibilizada é agregada por CEP e não identifica imóveis individuais.</p><p>As variáveis incluem exercício, categoria de uso, tipo de subunidade, padrão construtivo, quantidade de inscrições, valores venais, áreas, transações, ITIV, IPTU pago e TRSD lançada.</p></>},
  {title:'Organização dos CEPs',content:<><p>Os CEPs únicos de cada ano foram reunidos em <code>ceps_unicos_por_ano.xlsx</code> e padronizados como texto, sem hífen e com preservação dos zeros à esquerda.</p><p>A documentação registra 20.738 CEPs no texto e 20.739 na tabela de síntese. A diferença de uma unidade permanece registrada como divergência documental, sem correção por suposição.</p></>},
  {title:'Etapa 1 — georreferenciamento por CEP',content:<><p>O script <code>georreferenciamento_etapa_1.r</code> utilizou o pacote R <strong>geocodebr</strong> e a função <code>busca_por_cep()</code>. A base de referência é o CNEFE/IBGE e o sistema de referência documentado é SIRGAS 2000, EPSG:4674.</p><p>Em linguagem simples, esta etapa reúne os CEPs localizados diretamente pelas bases utilizadas pelo geocodebr. A documentação registra 15.600 ocorrências nessa primeira passagem; a base atualmente importada contém 15.579 pontos marcados como Etapa 1.</p></>},
  {title:'Etapa 2 — enriquecimento e georreferenciamento por endereço',content:<><p>Os CEPs ainda não localizados foram enriquecidos pela BrasilAPI com logradouro, bairro, localidade e UF. Depois, o geocodebr foi novamente usado, agora com as informações de endereço.</p><p>Os campos <code>gb_precisao</code> e <code>tipo_resultado</code> registram o tipo da correspondência. O primeiro caractere distingue correspondência determinística (<code>d</code>) de probabilística (<code>p</code>); o segundo informa o nível espacial. Foram aceitos no trabalho os códigos <code>dl01</code>, <code>dl03</code>, <code>dl04</code> e <code>pl01</code>.</p></>},
  {title:'Etapa 3 — validação e recuperação dos casos remanescentes',content:<><p>Os casos remanescentes passaram por geocodificação complementar e validação. O ViaCEP forneceu a referência do endereço; OpenStreetMap/Nominatim apoiou o confronto espacial; e a fórmula de Haversine mediu a distância entre resultados.</p><p>A documentação descreve as faixas: erro menor que 500 m, de 500 m a 2 km, maior ou igual a 2 km e sem dados. Essas faixas explicam a validação original e não alteram as métricas atuais da plataforma.</p></>},
  {title:'Consolidação final',content:<><p>As três etapas foram integradas em <code>123_consolidado_bruto.xlsx</code> e depois combinadas com a base original.</p><p>A base analítica desta aplicação contém 20.041 pontos válidos. Dois registros espacialmente incompatíveis com Salvador permanecem em quarentena auditável, com as coordenadas originais preservadas.</p></>},
  {title:'Qualidade e precisão das coordenadas',content:<><p>A precisão é heterogênea e depende da etapa e do método. Na base importada, <code>etapa</code> e <code>tipo_resultado</code> estão disponíveis para análise. A chave <code>precisao3</code> existe nos metadados, mas não possui valores preenchidos nos 20.041 pontos.</p><div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><p className="flex items-start gap-2 font-semibold"><AlertTriangle size={17} className="mt-0.5 shrink-0"/>Uma coordenada não representa necessariamente um imóvel individual.</p><p className="mt-2">Sem o número do imóvel, o resultado pode representar a posição estimada ou o ponto médio de um trecho do logradouro.</p></div></>},
  {title:'Limitações do georreferenciamento',content:<ul className="list-disc space-y-2 pl-5"><li>Ausência do número individual por sigilo fiscal e desidentificação.</li><li>Precisão desigual entre etapas, fontes e tipos de correspondência.</li><li>Possível representação pelo ponto médio do logradouro.</li><li>Dois registros mantidos em quarentena por incompatibilidade espacial.</li><li>A validação documental não elimina toda incerteza posicional.</li></ul>},
  {title:'Análise espacial em relação ao metrô',content:<><p>Esta é uma etapa posterior e separada do georreferenciamento original. As 440.902 distâncias ponto–estação são preservadas da matriz de origem e não são recalculadas.</p><Method label="CEP → percurso">A distância ao percurso é calculada pelo PostGIS sobre a geometria atualmente identificada como <code>provisional-track-v1</code>. O percurso ainda não é o traçado real validado.</Method><Method label="Variáveis preparadas para regressão"><code>within_100m</code>, <code>within_200m</code> e <code>within_300m</code> indicam se o ponto está dentro de cada raio. São variáveis exploratórias e não representam resultado causal.</Method><p>As faixas usadas para navegar no mapa não são necessariamente os mesmos limiares que serão usados na regressão econométrica.</p></>},
];

export function MethodologyPage(){return <section className="animate-in p-4 sm:p-6 lg:p-8"><PageHeader eyebrow="Metodologia documentada" title="Metodologia do Georreferenciamento" description="Como os CEPs foram organizados, georreferenciados, validados e preparados para a análise espacial." actions={<span className="inline-flex items-center gap-2 rounded-full border border-[#dbe3de] bg-white px-3 py-1.5 text-xs font-semibold text-[#5f6b66]"><Clock3 size={13}/>Atualizado em 2026</span>}/><MethodSummary/><div className="grid gap-5 xl:grid-cols-[270px_minmax(0,820px)]"><aside className="h-fit rounded-2xl border border-[#dfe5e1] bg-white p-3 xl:sticky xl:top-24"><p className="px-2 py-2 text-[10px] font-semibold uppercase tracking-[.1em] text-[#8a9490]">Neste documento</p>{sections.map((section,index)=><a key={section.title} href={`#metodo-${index}`} className="block rounded-lg px-2 py-2 text-xs font-medium text-[#65716c] hover:bg-[#eef3f0] hover:text-[#176b52]">{section.title}</a>)}</aside><article className="rounded-[22px] border border-[#dfe5e1] bg-white px-6 py-3 sm:px-9">{sections.map((section,index)=><section key={section.title} id={`metodo-${index}`} className="border-b border-[#e8ece9] py-7 last:border-0"><div className="flex items-start gap-2"><span className="mt-1 font-mono text-[10px] font-semibold text-[#8a9892]">{String(index+1).padStart(2,'0')}</span><h2 className="text-base font-semibold tracking-[-.02em]">{section.title}</h2></div><div className="mt-3 space-y-3 text-sm leading-7 text-[#66736e]">{section.content}</div></section>)}</article></div><div className="mt-5 flex max-w-[1090px] items-start gap-3 rounded-2xl bg-[#1b2b25] p-4 text-white"><BookOpenText size={18} className="mt-0.5 shrink-0 text-[#8bc8ad]"/><div><p className="text-xs font-semibold">Fonte principal</p><p className="mt-1 text-[11px] leading-5 text-white/60">“Documentação do trabalho de georreferenciamento_.docx”. A metodologia metroviária permanece separada e versionada.</p></div><Info size={14} className="ml-auto text-white/35"/></div></section>;}

function Method({label,children}:{label:string;children:ReactNode}){return <div className="rounded-xl border border-[#e1e7e3] bg-[#f8faf9] p-4"><p className="text-xs font-semibold text-[#32413b]">{label}</p><p className="mt-1 text-sm leading-6">{children}</p></div>;}

function MethodSummary(){const steps=['Base de CEPs','Tentativa direta','Enriquecimento','Validação complementar','Base georreferenciada final','Análise de proximidade com o metrô'];return <section className="mb-5 rounded-[22px] border border-[#d9e3dd] bg-white p-5"><h2 className="text-base font-semibold">Em resumo</h2><p className="mt-1 text-xs text-[#74807b]">O caminho dos dados, da organização inicial à análise espacial.</p><div className="mt-4 flex flex-wrap items-center gap-2">{steps.map((label,index)=><div key={label} className="flex items-center gap-2"><span className="rounded-xl border border-[#dce5e0] bg-[#f4f8f5] px-3 py-2 text-xs font-semibold text-[#405049]">{label}</span>{index<steps.length-1&&<span aria-hidden="true" className="text-[#8a9892]">→</span>}</div>)}</div></section>;}
