'use client';

import { CircleHelp, Info } from 'lucide-react';
import { PageHeader } from '@/components/page-header';
import { loadAnalysisDistributions, loadDescriptiveStats, loadEcdf, loadGeocodingQualitySummary, loadHistogram, loadQuarantinedStudyPoints, loadScatterAndComparisons } from '@/lib/supabase/queries';
import type { DescriptiveStats, DistanceRangeDistribution, EcdfPoint, GeocodingQualitySummary, GroupComparison, HistogramBin, QuarantinedStudyPoint, ScatterPoint } from '@/types/study';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis, ZAxis } from 'recharts';

const metricLabels={station:'Distância até a estação',track:'Distância até o percurso provisório'};
const stageHelp:Record<string,string>={
  '1':'Tentativa de localizar o CEP diretamente nas bases do geocodebr.',
  '2':'Os CEPs não resolvidos receberam informações adicionais de endereço e foram processados novamente.',
  '3':'Os casos restantes passaram por tratamento adicional e validações espaciais.',
};
const resultHelp:Record<string,string>={
  dl01:'Correspondência em nível de logradouro com maior precisão disponível para a base sem número do imóvel.',
  dl03:'Outra classe determinística de correspondência em nível de logradouro aceita no trabalho documentado.',
  dl04:'Outra classe determinística de correspondência em nível de logradouro aceita no trabalho documentado.',
  pl01:'Correspondência probabilística de logradouro aceita após os critérios de similaridade e consistência geográfica.',
  outros:'Outros códigos efetivamente encontrados nos metadados importados.',
};
const annualCoverage=[
  {year:2011,unique:13454,initialCount:10516,enrichedCount:11787,finalCount:12168,initial:78.16,enriched:87.61,final:90.44},{year:2012,unique:13753,initialCount:10739,enrichedCount:12049,finalCount:12444,initial:78.08,enriched:87.61,final:90.48},
  {year:2013,unique:14167,initialCount:11036,enrichedCount:12414,finalCount:12823,initial:77.90,enriched:87.63,final:90.51},{year:2014,unique:19026,initialCount:14571,enrichedCount:16497,finalCount:17219,initial:76.58,enriched:86.71,final:90.50},
  {year:2015,unique:19105,initialCount:14627,enrichedCount:16567,finalCount:17290,initial:76.56,enriched:86.72,final:90.50},{year:2016,unique:19212,initialCount:14703,enrichedCount:16665,finalCount:17388,initial:76.53,enriched:86.74,final:90.51},
  {year:2017,unique:19245,initialCount:14745,enrichedCount:16712,finalCount:17433,initial:76.62,enriched:86.84,final:90.58},{year:2018,unique:19291,initialCount:14775,enrichedCount:16752,finalCount:17477,initial:76.59,enriched:86.84,final:90.60},
  {year:2019,unique:19266,initialCount:14793,enrichedCount:16775,finalCount:17491,initial:76.78,enriched:87.07,final:90.79},{year:2020,unique:19310,initialCount:14809,enrichedCount:16801,finalCount:17519,initial:76.69,enriched:87.01,final:90.73},
  {year:2021,unique:19422,initialCount:14867,enrichedCount:16872,finalCount:17598,initial:76.55,enriched:86.87,final:90.61},{year:2022,unique:19524,initialCount:14948,enrichedCount:16964,finalCount:17703,initial:76.56,enriched:86.89,final:90.67},
  {year:2023,unique:19638,initialCount:15254,enrichedCount:17197,finalCount:17932,initial:77.68,enriched:87.57,final:91.31},{year:2024,unique:18995,initialCount:15223,enrichedCount:16863,finalCount:17539,initial:80.14,enriched:88.78,final:92.33},
];

export function AnalysisPage(){
  const [stats,setStats]=useState<DescriptiveStats[]>([]);const [stationHist,setStationHist]=useState<HistogramBin[]>([]);const [trackHist,setTrackHist]=useState<HistogramBin[]>([]);
  const [stationEcdf,setStationEcdf]=useState<EcdfPoint[]>([]);const [trackEcdf,setTrackEcdf]=useState<EcdfPoint[]>([]);const [scatter,setScatter]=useState<ScatterPoint[]>([]);const [groups,setGroups]=useState<GroupComparison[]>([]);const [quality,setQuality]=useState<GeocodingQualitySummary[]>([]);const [quarantined,setQuarantined]=useState<QuarantinedStudyPoint[]>([]);const [distanceRanges,setDistanceRanges]=useState<DistanceRangeDistribution[]>([]);
  const [binWidth,setBinWidth]=useState(250);const [dimension,setDimension]=useState<GroupComparison['dimension']>('line');const [loading,setLoading]=useState(true);const [error,setError]=useState(false);
  useEffect(()=>{Promise.all([loadDescriptiveStats(),loadEcdf('station',50),loadEcdf('track',50),loadScatterAndComparisons(),loadGeocodingQualitySummary(),loadQuarantinedStudyPoints(),loadAnalysisDistributions()]).then(([nextStats,nextStationEcdf,nextTrackEcdf,other,nextQuality,nextQuarantined,distributions])=>{setStats(nextStats);setStationEcdf(nextStationEcdf);setTrackEcdf(nextTrackEcdf);setScatter(other.scatter);setGroups(other.groups);setQuality(nextQuality);setQuarantined(nextQuarantined);setDistanceRanges(distributions.ranges);}).catch(()=>setError(true)).finally(()=>setLoading(false));},[]);
  useEffect(()=>{const controller=new AbortController();Promise.all([loadHistogram('station',binWidth,controller.signal),loadHistogram('track',binWidth,controller.signal)]).then(([station,track])=>{setStationHist(station);setTrackHist(track);}).catch((nextError)=>{if(nextError?.name!=='AbortError')setError(true);});return()=>controller.abort();},[binWidth]);
  const ecdf=useMemo(()=>mergeEcdf(stationEcdf,trackEcdf),[stationEcdf,trackEcdf]);
  const comparison=useMemo(()=>groups.filter((item)=>item.dimension===dimension).sort((a,b)=>b.n-a.n).slice(0,dimension==='locality'?12:20),[groups,dimension]);
  const stages=quality.filter((item)=>item.dimension==='stage').sort((a,b)=>a.group_value.localeCompare(b.group_value));
  const resultTypes=useMemo(()=>summarizeResultTypes(quality),[quality]);
  const precisao3=quality.filter((item)=>item.dimension==='precisao3');
  const valid=quality.find((item)=>item.dimension==='status'&&item.group_value==='valid')?.n;
  const quarantine=2; // Total validado do estudo; os registros detalhados permanecem privados na quarentena.
  const dl01=resultTypes.find((item)=>item.group_value==='dl01')?.n;
  const stationStats=stats.find((item)=>item.metric==='station');const trackStats=stats.find((item)=>item.metric==='track');
  const milestones=[100,250,500,1000,2000].map((threshold)=>({threshold,percentage:atThreshold(trackEcdf,threshold)}));
  const track500=atThreshold(trackEcdf,500);const track1000=atThreshold(trackEcdf,1000);
  const lineGroups=groups.filter((item)=>item.dimension==='line').sort((a,b)=>b.n-a.n);const majorityLine=lineGroups[0];
  const exampleStart=binWidth*4;const exampleEnd=binWidth*5;
  const stageTitles:Record<string,string>={'1':'Localização direta por CEP','2':'Localização após complementar o endereço','3':'Localização e validação complementar'};
  const baseSummary=[
    {label:'CEPs georreferenciados válidos',value:(valid??20041).toLocaleString('pt-BR'),help:'Pontos/CEPs mantidos na base espacial principal depois das validações.'},
    {label:'CEPs preservados em quarentena',value:quarantine.toLocaleString('pt-BR'),help:'Registros preservados para auditoria, mas excluídos dos cálculos principais.'},
    {label:'Total originalmente analisado nesta matriz',value:'20.043',help:'Soma dos 20.041 pontos válidos com os 2 registros preservados em quarentena.'},
    {label:'Relações CEP × estação',value:'440.902',help:'Distâncias válidas já presentes na matriz original: 20.041 CEPs multiplicados por 22 estações.'},
    {label:'Estações consideradas',value:'22',help:'Estações relacionadas a cada CEP na matriz de distâncias.'},
    {label:'Linhas de metrô',value:'2',help:'Linha 1 e Linha 2 consideradas na exploração espacial atual.'},
  ];

  return <section className="animate-in p-4 sm:p-6 lg:p-8"><PageHeader eyebrow="Análise estatística" title="O que as distâncias mostram?" description="Leitura descritiva dos 20.041 pontos válidos, sem atribuir efeitos causais ao metrô."/>
    <section className="mb-4 rounded-[22px] border border-[#dce4df] bg-white p-5"><h2 className="text-base font-semibold">Cobertura do georreferenciamento</h2><p className="mt-1 text-xs leading-5 text-[#77827e]">Evolução histórica documentada para o universo consolidado de <strong>20.739 CEPs únicos</strong>. Esta cobertura descreve o trabalho de georreferenciamento; não é a mesma população da matriz metroviária atual.</p>
      <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{[
        {label:'Universo histórico de CEPs únicos',value:'20.739',help:'Denominador da tabela consolidada das etapas de georreferenciamento.'},
        {label:'Localização direta por CEP',value:'15.579 · 75,12%',help:'Resultado consolidado da Etapa 1; aproximadamente 15,6 mil CEPs.'},
        {label:'Após complementar o endereço',value:'17.783 · 85,75%',help:'Cobertura acumulada depois da Etapa 2 de enriquecimento.'},
        {label:'Após validação complementar',value:'18.620 · 89,78%',help:'Cobertura histórica final acumulada após a Etapa 3.'},
        {label:'Base metroviária atual',value:'20.041 válidos',help:'Pontos válidos presentes hoje na matriz ponto–estação; universo distinto do histórico.'},
        {label:'Quarentena auditável',value:'2 registros',help:'Coordenadas originais preservadas, mas excluídas da análise espacial principal.'},
      ].map((item)=><article key={item.label} title={item.help} className="rounded-2xl border border-[#e0e6e2] bg-[#fafbfa] p-4"><p className="flex items-start gap-1.5 text-xs font-medium text-[#68746f]">{item.label}<CircleHelp size={13} className="mt-0.5 shrink-0 text-[#8b9691]"/></p><p className="mt-3 text-xl font-semibold tracking-[-.035em]">{item.value}</p><p className="mt-1 text-[10px] leading-4 text-[#8a9490]">{item.help}</p></article>)}</div>
      <article className="mt-4 rounded-2xl border border-[#e0e6e2] p-4"><h3 className="text-sm font-semibold">Como a cobertura aumentou durante o georreferenciamento?</h3><p className="mt-1 text-[11px] text-[#7d8884]">Cada etapa recuperou CEPs que não haviam sido localizados com precisão suficiente na etapa anterior.</p><div className="mt-4 space-y-2">{[
        {label:'CEPs únicos no universo histórico',value:20739,color:'#26332f'},
        {label:'Localização direta por CEP',value:15579,color:'#78998b'},
        {label:'Após complementar o endereço',value:17783,color:'#3f8069'},
        {label:'Após validação complementar',value:18620,color:'#176b52'},
      ].map((item)=><div key={item.label}><div className="mb-1 flex justify-between gap-3 text-[11px]"><span>{item.label}</span><strong>{item.value.toLocaleString('pt-BR')}</strong></div><div className="h-3 overflow-hidden rounded-full bg-[#edf1ee]"><div className="h-full rounded-full" style={{width:`${item.value/20739*100}%`,background:item.color}}/></div></div>)}</div></article>
      <article className="mt-4 rounded-2xl border border-[#e0e6e2] p-4"><h3 className="text-sm font-semibold">Cobertura do georreferenciamento por ano</h3><p className="mt-1 text-[11px] leading-5 text-[#7d8884]">Percentual de CEPs únicos de cada exercício localizado em cada marco acumulado, conforme a tabela anual documentada de 2011 a 2024.</p><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2">{[{label:'Localização direta',color:'#78998b'},{label:'Após complementar endereço',color:'#3f8069'},{label:'Após validação complementar',color:'#176b52'}].map((item)=><span key={item.label} className="inline-flex items-center gap-2 text-[11px] font-medium text-[#53615c]"><span className="h-0.5 w-7 rounded-full" style={{background:item.color}}/>{item.label}</span>)}</div><ResponsiveContainer width="100%" height={280}><LineChart data={annualCoverage} margin={{left:4,right:18,top:20,bottom:5}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="year"/><YAxis domain={[70,100]} unit="%"/><Tooltip content={<CoverageTooltip/>}/><Line type="monotone" dataKey="initial" name="Localização direta" stroke="#78998b" strokeWidth={2}/><Line type="monotone" dataKey="enriched" name="Após complementar endereço" stroke="#3f8069" strokeWidth={2}/><Line type="monotone" dataKey="final" name="Após validação complementar" stroke="#176b52" strokeWidth={2.5}/></LineChart></ResponsiveContainer><div className="mt-3 rounded-xl bg-[#f3f6f4] p-3 text-[11px] leading-5 text-[#66736e]"><strong>Como ler este gráfico?</strong><p className="mt-1">Cada linha mostra o percentual de CEPs que já havia sido localizado após cada etapa do processo. Quanto mais alta a linha, maior a cobertura do georreferenciamento.</p><p className="mt-2"><strong>Localização direta:</strong> percentual obtido somente com a primeira tentativa de georreferenciamento.</p><p><strong>Após complementar endereço:</strong> cobertura acumulada depois de adicionar informações de endereço e processar novamente os CEPs não localizados.</p><p><strong>Após validação complementar:</strong> cobertura acumulada depois da etapa adicional de tratamento e validação.</p></div><p className="mt-3 text-[11px] font-medium text-[#6d5a24]">Os percentuais representam coberturas acumuladas do processo de georreferenciamento. Não são três grupos independentes de CEPs.</p></article>
      <p className="mt-4 rounded-xl bg-[#fff8e8] p-3 text-[11px] leading-5 text-[#6d5a24]"><strong>Não confundir os universos:</strong> Os números de cobertura do georreferenciamento descrevem o processo histórico de localização dos CEPs da base imobiliária. Já os 20.041 pontos representam a base válida atualmente utilizada na análise espacial do metrô. Outros 2 registros permanecem preservados em quarentena.</p>
    </section>
    <div className="mb-4 rounded-2xl border border-[#ead9ad] bg-[#fff9e9] p-4 text-xs leading-5 text-[#6d5a24]"><Info size={15} className="mr-2 inline text-[#9b7620]"/><strong>Sobre as medidas:</strong> a distância até a estação vem da matriz original. A distância até o percurso usa o traçado <code>provisional-track-v1</code>, que ainda é provisório.</div>
    {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-800">Não foi possível carregar uma ou mais análises. Tente atualizar a página.</div>}

    <section className="rounded-[22px] border border-[#dce4df] bg-white p-5"><h2 className="text-base font-semibold">Resumo da base georreferenciada</h2><p className="mt-1 text-xs text-[#77827e]">Visão geral da matriz e das observações preservadas para auditoria.</p><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{baseSummary.map((item)=><article key={item.label} title={item.help} className="rounded-2xl border border-[#e0e6e2] bg-[#fafbfa] p-4"><p className="flex items-start gap-1.5 text-xs font-medium text-[#68746f]">{item.label}<CircleHelp size={13} className="mt-0.5 shrink-0 text-[#8b9691]"/></p><p className="mt-3 text-2xl font-semibold tracking-[-.04em]">{item.value}</p><p className="mt-1 text-[10px] leading-4 text-[#8a9490]">{item.help}</p></article>)}</div></section>

    <section className="mt-4 rounded-[22px] border border-[#dce4df] bg-white p-5"><div><h2 className="text-base font-semibold">Qualidade e precisão das coordenadas</h2><p className="mt-1 text-xs leading-5 text-[#77827e]">Indicadores calculados somente com <code>etapa</code> e <code>tipo_resultado</code> presentes em <code>study_points.source_metadata</code>.</p></div>
      {valid&&dl01&&<article className="mt-4 rounded-2xl border border-[#cfe1d8] bg-[#edf6f1] p-4"><p className="text-sm font-semibold text-[#214c3d]">Maior precisão disponível em nível de logradouro</p><div className="mt-2 flex flex-wrap items-end gap-x-4 gap-y-1"><p className="text-3xl font-semibold tracking-[-.04em] text-[#176b52]">{percentage(dl01,valid)}</p><p className="pb-1 text-sm font-medium text-[#50665e]">{dl01.toLocaleString('pt-BR')} pontos</p></div><p className="mt-2 text-xs leading-5 text-[#5e716a]">Correspondência em nível de logradouro com maior precisão disponível para a base sem número do imóvel.</p><p className="mt-1 font-mono text-[10px] text-[#84918b]">Código técnico: dl01</p></article>}
      <div className="mt-5 grid gap-4 xl:grid-cols-2"><article className="rounded-2xl border border-[#e0e6e2] p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="text-sm font-semibold">Como os pontos foram localizados?</h3><p className="mt-1 text-[11px] text-[#7d8884]">As etapas mostram o caminho necessário para localizar cada CEP.</p></div><details className="relative"><summary className="cursor-pointer list-none rounded-lg border border-[#d8e1dc] px-3 py-2 text-[11px] font-semibold text-[#176b52]">O que aconteceu nesta etapa?</summary><div className="mt-2 rounded-xl bg-[#f3f6f4] p-3 text-[11px] leading-5 text-[#65716c]"><p><strong>Etapa 1:</strong> {stageHelp['1']}</p><p><strong>Etapa 2:</strong> {stageHelp['2']}</p><p><strong>Etapa 3:</strong> {stageHelp['3']}</p></div></details></div><div className="mt-3 space-y-3">{stages.map((item)=><div key={item.group_value} className="rounded-xl bg-[#f3f6f4] p-3" title={stageHelp[item.group_value]}><p className="text-[10px] font-semibold uppercase tracking-[.08em] text-[#87928d]">Etapa {item.group_value} do georreferenciamento</p><div className="mt-1 flex items-end justify-between gap-3"><p className="text-xs font-semibold text-[#35413d]">{stageTitles[item.group_value]??`Etapa ${item.group_value}`}</p><span className="text-lg font-semibold text-[#176b52]">{percentage(item.n,valid??0)}</span></div><p className="mt-1 text-[11px] font-medium text-[#53615b]">{item.n.toLocaleString('pt-BR')} pontos</p><p className="mt-1 text-[11px] leading-5 text-[#6c7873]">{stageHelp[item.group_value]??'Etapa registrada nos metadados importados.'}</p></div>)}</div></article>
        <article className="rounded-2xl border border-[#e0e6e2] p-4"><h3 className="text-sm font-semibold">Precisão registrada pelo geocodebr</h3><p className="mt-1 text-[11px] text-[#7d8884]">Quantidade e percentual por <code>tipo_resultado</code>; o código aparece apenas como referência técnica.</p><div className="mt-3 space-y-2">{resultTypes.map((item)=><div key={item.group_value} className="rounded-xl border border-[#e6ebe8] p-3" title={`Código original: ${item.group_value}`}><div className="flex justify-between gap-3"><p className="text-xs font-semibold">{friendlyResult(item.group_value)}</p><span className="text-xs font-semibold text-[#176b52]">{percentage(item.n,valid??0)}</span></div><p className="mt-1 text-[11px] leading-5 text-[#6e7a75]">{resultHelp[item.group_value]??resultHelp.outros}</p><p className="mt-1 text-[10px] text-[#7f8b86]">{item.n.toLocaleString('pt-BR')} pontos · código <span className="font-mono">{item.group_value}</span></p></div>)}</div></article></div>
      {precisao3.length===0?<p className="mt-4 rounded-xl border border-dashed border-[#d8dfdb] bg-[#fafbfa] p-3 text-[11px] leading-5 text-[#6f7b76]"><strong>Precisao3:</strong> a chave foi preservada em todos os registros, mas não contém valores preenchidos. Por isso não foram inventadas categorias como “exato” ou “impreciso”.</p>:<div className="mt-4 grid gap-2 sm:grid-cols-3">{precisao3.map((item)=><div key={item.group_value} className="rounded-xl bg-[#f3f6f4] p-3"><p className="text-xs font-semibold capitalize">{item.group_value}</p><p className="mt-1 text-sm">{item.n.toLocaleString('pt-BR')} · {percentage(item.n,valid??0)}</p></div>)}</div>}
      <p className="mt-4 text-[11px] leading-5 text-[#68746f]"><strong>Validação documentada:</strong> ViaCEP foi usado como referência de endereço; OpenStreetMap/Nominatim apoiou a validação espacial; Haversine mediu as diferenças. As faixas &lt;500 m, 500 m–2 km, ≥2 km e sem dados descrevem esse procedimento histórico e não reclassificam os dados atuais.</p>
    </section>

    <section className="mt-4 rounded-[22px] border border-[#ead9ad] bg-white p-5"><h2 className="text-base font-semibold">Pontos fora da análise principal</h2><p className="mt-1 text-xs leading-5 text-[#77827e]">Esses registros foram preservados para auditoria, mas não entram nos cálculos principais porque suas coordenadas são incompatíveis com a área esperada de Salvador.</p><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-xs"><thead><tr className="border-b border-[#e4e9e6] bg-[#fafbfa] text-[10px] uppercase tracking-wide text-[#77827e]">{['CEP','Logradouro','Localidade','Latitude original','Longitude original','Motivo','Observação da validação','Data da quarentena'].map((label)=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{quarantined.map((row)=><tr key={`${row.cep}-${row.latitude_original}`} className="border-b border-[#edf0ee] align-top"><td className="px-3 py-3 font-mono">{row.cep??'—'}</td><td className="px-3 py-3">{row.street??'—'}</td><td className="px-3 py-3">{row.locality??'—'}</td><td className="px-3 py-3 font-mono">{row.latitude_original}</td><td className="px-3 py-3 font-mono">{row.longitude_original}</td><td className="px-3 py-3 font-mono text-[10px]">{row.reason}</td><td className="max-w-xs px-3 py-3 leading-5">{row.validation_note??'—'}</td><td className="px-3 py-3">{new Date(row.quarantined_at).toLocaleString('pt-BR')}</td></tr>)}</tbody></table>{!loading&&quarantined.length===0&&<p className="p-4 text-xs text-[#77827e]">Nenhum registro de quarentena foi retornado.</p>}</div></section>

    <DistanceZonesSection ranges={distanceRanges}/>

    <section className="mt-4 rounded-[22px] bg-[#193128] p-5 text-white"><h2 className="text-base font-semibold">O que os dados estão nos dizendo?</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{track1000!==undefined&&<Insight>{formatPercent(100-track1000)} dos CEPs estão a mais de 1 km do percurso provisório.</Insight>}{stationStats&&<Insight>A mediana indica que metade dos CEPs está a até {kilometers(stationStats.p50_m)} da estação mais próxima.</Insight>}{majorityLine&&valid&&<Insight>A maior parte dos pontos tem a {majorityLine.group_value} como linha mais próxima: {percentage(majorityLine.n,valid)}.</Insight>}{track500!==undefined&&<Insight>{formatPercent(track500)} dos pontos ficam a até 500 m do percurso provisório.</Insight>}</div><p className="mt-3 text-[10px] text-white/55">Insights descritivos calculados automaticamente. Eles não demonstram valorização, redução de preços ou qualquer outro efeito causal.</p></section>

    <article className="mt-4 rounded-[22px] border border-[#dce4df] bg-white p-5"><h2 className="text-base font-semibold">Estatísticas descritivas</h2><p className="mt-1 text-xs text-[#77827e]">Resumo das duas medidas em metros. N = {stationStats?.n?.toLocaleString('pt-BR')??'…'}.</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[860px] text-right text-xs"><thead><tr className="border-b border-[#e3e8e5] text-[10px] uppercase tracking-wide text-[#79847f]"><th className="px-3 py-3 text-left">Medida</th>{['N','Média','Mediana','Desvio padrão','Mínimo','P10','P25','P50','P75','P90','P95','Máximo'].map((label)=><th key={label} className="px-3 py-3">{label}</th>)}</tr></thead><tbody>{stats.map((row)=><tr key={row.metric} className="border-b border-[#edf0ee]"><td className="px-3 py-3 text-left font-semibold">{metricLabels[row.metric]}</td><td className="px-3 py-3">{row.n.toLocaleString('pt-BR')}</td>{[row.mean_m,row.p50_m,row.stddev_m,row.min_m,row.p10_m,row.p25_m,row.p50_m,row.p75_m,row.p90_m,row.p95_m,row.max_m].map((value,index)=><td key={index} className="px-3 py-3 font-mono text-[11px]">{meters(value)}</td>)}</tr>)}</tbody></table></div></article>

    <div className="mt-4 flex flex-wrap items-center justify-end gap-2 text-xs"><label htmlFor="distance-group" className="inline-flex items-center gap-1.5 font-medium">Agrupar distâncias de:<span title="Define o tamanho dos grupos utilizados no gráfico. Com 250 metros, a primeira barra representa pontos entre 0 e 250 m, a segunda entre 250 e 500 m, e assim por diante."><CircleHelp size={14} className="text-[#7c8883]"/></span></label><select id="distance-group" value={binWidth} onChange={(event)=>setBinWidth(Number(event.target.value))} className="rounded-lg border border-[#d8e0dc] bg-white px-3 py-2">{[100,250,500,1000].map((value)=><option key={value} value={value}>{value.toLocaleString('pt-BR')} metros</option>)}</select></div>
    <div className="mt-3 grid gap-4 xl:grid-cols-2"><ChartCard title="Quão perto os CEPs estão das estações?" subtitle="Cada barra mostra quantos CEPs estão dentro de um intervalo de distância da estação mais próxima." n={stationHist[0]?.total_n} interpretation={`Uma barra entre ${humanDistance(exampleStart)} e ${humanDistance(exampleEnd)} representa quantos CEPs estão nesse intervalo da estação mais próxima.`}><Histogram data={stationHist}/></ChartCard><ChartCard title="Quão perto os CEPs estão do percurso do metrô?" subtitle="Cada barra mostra quantos CEPs estão a determinada distância do percurso atualmente estimado do metrô. Este percurso ainda é provisório." n={trackHist[0]?.total_n} interpretation={`Uma barra entre ${humanDistance(exampleStart)} e ${humanDistance(exampleEnd)} representa quantos CEPs estão nesse intervalo do percurso provisório.`}><Histogram data={trackHist}/></ChartCard></div>

    <div className="mt-4 grid gap-4 xl:grid-cols-[1.15fr_1fr]"><ChartCard title="Qual percentual dos CEPs está a até determinada distância?" subtitle="Curva acumulada das distâncias (ECDF): cada ponto mostra o percentual alcançado até aquele limite." n={stationStats?.n} interpretation="Se a curva estiver em 60% na marca de 2 km, significa que 60% dos CEPs analisados estão a até 2 km."><ResponsiveContainer width="100%" height={290}><LineChart data={ecdf} margin={{left:8,right:18,top:10,bottom:5}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="threshold_m" tickFormatter={compactMeters}/><YAxis domain={[0,100]} unit="%"/><Tooltip/><Legend/><Line type="monotone" dataKey="station" name="Estação" stroke="#26332f" dot={false}/><Line type="monotone" dataKey="track" name="Percurso" stroke="#d96f2d" dot={false}/>{[100,250,500,1000,2000].map((value)=><ReferenceLine key={value} x={value} stroke="#b9c2bd" strokeDasharray="2 4"/>)}</LineChart></ResponsiveContainer><div className="mt-3 flex flex-wrap gap-2">{milestones.map((item)=><span key={item.threshold} className="rounded-full bg-[#f1f5f2] px-2.5 py-1 text-[10px] text-[#5e6b66]">Até {humanDistance(item.threshold)}: <strong>{item.percentage===undefined?'…':formatPercent(item.percentage)}</strong></span>)}</div></ChartCard>
      <ChartCard title="Proximidade da estação versus proximidade do percurso" subtitle="Cada ponto representa um CEP; a amostra é determinística e as estatísticas usam toda a base." n={scatter.length} interpretation="Quanto mais perto do canto inferior esquerdo, mais perto o CEP está tanto de uma estação quanto do percurso. Acima/esquerda significa perto do percurso e longe da estação; abaixo/direita, perto da estação e longe do percurso; acima/direita, longe de ambos. Isso não é correlação causal."><ResponsiveContainer width="100%" height={290}><ScatterChart margin={{left:8,right:16,top:10,bottom:5}}><CartesianGrid/><XAxis type="number" dataKey="distance_line_m" name="Percurso" unit=" m" tickFormatter={compactMeters}/><YAxis type="number" dataKey="distance_station_m" name="Estação" unit=" m" tickFormatter={compactMeters}/><ZAxis range={[18,18]}/><Tooltip cursor={{strokeDasharray:'3 3'}}/><Scatter data={scatter} fill="#24745c" fillOpacity={0.45}/>{trackStats&&<ReferenceLine x={trackStats.p50_m} stroke="#d96f2d" strokeDasharray="4 4"/>}{stationStats&&<ReferenceLine y={stationStats.p50_m} stroke="#26332f" strokeDasharray="4 4"/>}</ScatterChart></ResponsiveContainer></ChartCard></div>

    <article className="mt-4 rounded-[22px] border border-[#dce4df] bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-semibold">Comparações entre grupos</h2><p className="mt-1 text-xs text-[#77827e]">Médias por linha mais próxima, localidade e precisão disponível.</p></div><div className="flex rounded-xl bg-[#eef2ef] p-1">{([['line','Linhas'],['locality','Localidades'],['geocoding_quality','Geocodificação']] as const).map(([value,label])=><button key={value} onClick={()=>setDimension(value)} className={`rounded-lg px-3 py-2 text-[11px] font-semibold ${dimension===value?'bg-white text-[#176b52] shadow-sm':'text-[#6f7b76]'}`}>{label}</button>)}</div></div><p className="mt-3 text-[11px] text-[#6f7b76]">N total exibido: {comparison.reduce((sum,item)=>sum+item.n,0).toLocaleString('pt-BR')}. Para localidades, aparecem as 12 com maior N.</p><ResponsiveContainer width="100%" height={330}><BarChart data={comparison} margin={{left:8,right:18,top:20,bottom:dimension==='locality'?85:35}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="group_value" interval={0} angle={dimension==='locality'?-38:0} textAnchor={dimension==='locality'?'end':'middle'} height={dimension==='locality'?100:45}/><YAxis tickFormatter={compactMeters} unit=" m"/><Tooltip/><Legend/><Bar dataKey="mean_station_m" name="Média até estação" fill="#26332f"/><Bar dataKey="mean_line_m" name="Média até percurso" fill="#d96f2d"/></BarChart></ResponsiveContainer><Interpretation>Compare as alturas dentro de cada grupo e observe o N. Diferenças descritivas não identificam causalidade.</Interpretation></article>

    <section className="mt-4 rounded-[22px] border border-[#d9e4de] bg-[#f4f8f5] p-5"><h2 className="text-sm font-semibold">Variáveis preparadas para análise econométrica</h2><p className="mt-2 text-xs leading-5 text-[#65726d]"><code>within_100m</code>, <code>within_200m</code> e <code>within_300m</code> indicam se o ponto está ou não dentro de cada raio do percurso. Ainda não representam resultado causal.</p><p className="mt-2 text-[11px] text-[#7b8782]">As faixas utilizadas para explorar o mapa não são necessariamente os mesmos limiares que serão usados na regressão econométrica.</p></section>
    {loading&&<div className="fixed bottom-5 right-5 rounded-full bg-[#17241f] px-4 py-2 text-xs text-white shadow-lg">Calculando estatísticas…</div>}
  </section>;
}

function Histogram({data}:{data:HistogramBin[]}){return <ResponsiveContainer width="100%" height={260}><BarChart data={data} margin={{left:8,right:12,top:10,bottom:5}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="bin_start_m" tickFormatter={compactMeters}/><YAxis/><Tooltip formatter={(value)=>[Number(value).toLocaleString('pt-BR'),'CEPs']} labelFormatter={(value)=>`A partir de ${humanDistance(Number(value))}`}/><Bar dataKey="n" name="CEPs" fill="#2b8065"/></BarChart></ResponsiveContainer>;}
function CoverageTooltip({active,payload}:{active?:boolean;payload?:readonly {payload:(typeof annualCoverage)[number]}[]}){const row=payload?.[0]?.payload;if(!active||!row)return null;return <div className="rounded-xl border border-[#dce4df] bg-white p-3 text-[11px] leading-5 shadow-xl"><p className="font-semibold text-[#26332f]">Ano: {row.year}</p><p className="mt-1"><span className="text-[#78998b]">Localização direta:</span> <strong>{formatPercent(row.initial)}</strong></p><p><span className="text-[#3f8069]">Após complementar endereço:</span> <strong>{formatPercent(row.enriched)}</strong></p><p><span className="text-[#176b52]">Após validação complementar:</span> <strong>{formatPercent(row.final)}</strong></p><p className="mt-1 border-t border-[#e5eae7] pt-1">CEPs únicos: <strong>{row.unique.toLocaleString('pt-BR')}</strong></p></div>;}
function ChartCard({title,subtitle,n,interpretation,children}:{title:string;subtitle:string;n?:number;interpretation:string;children:ReactNode}){return <article className="rounded-[22px] border border-[#dce4df] bg-white p-5"><h2 className="text-sm font-semibold">{title}</h2><p className="mt-1 text-[11px] leading-5 text-[#7d8884]">{subtitle} · N = {n?.toLocaleString('pt-BR')??'…'}</p><div className="mt-4">{children}</div><Interpretation>{interpretation}</Interpretation></article>;}
function Interpretation({children}:{children:ReactNode}){return <p className="mt-4 rounded-xl bg-[#f3f6f4] p-3 text-[11px] leading-5 text-[#66736e]"><strong>Como ler este gráfico?</strong> {children}</p>;}
function Insight({children}:{children:ReactNode}){return <p className="rounded-xl bg-white/8 p-3 text-xs leading-5 text-white/80">{children}</p>;}
function DistanceZonesSection({ranges}:{ranges:DistanceRangeDistribution[]}){
  const ordered=[...ranges].sort((a,b)=>Number(a.sort_order)-Number(b.sort_order));
  const total=ordered.reduce((sum,item)=>sum+Number(item.point_count),0);
  const counts=new Map(ordered.map((item)=>[item.code,Number(item.point_count)]));
  const cumulative=[
    {label:'Até 100 m',count:(counts.get('0_50')??0)+(counts.get('50_100')??0)},
    {label:'Até 250 m',count:(counts.get('0_50')??0)+(counts.get('50_100')??0)+(counts.get('100_250')??0)},
    {label:'Até 500 m',count:(counts.get('0_50')??0)+(counts.get('50_100')??0)+(counts.get('100_250')??0)+(counts.get('250_500')??0)},
    {label:'Até 1 km',count:ordered.filter((item)=>item.code!=='gt_1000').reduce((sum,item)=>sum+Number(item.point_count),0)},
    {label:'Acima de 1 km',count:counts.get('gt_1000')??0},
  ];
  const labels:Record<string,string>={'0_50':'0–50 m','50_100':'50–100 m','100_250':'100–250 m','250_500':'250–500 m','500_1000':'500 m–1 km','gt_1000':'Acima de 1 km'};
  const explanations:Record<string,string>={'0_50':'Muito próximo do percurso.','50_100':'Entre 50 e 100 metros do percurso.','100_250':'Entre 100 e 250 metros do percurso.','250_500':'Entre 250 e 500 metros do percurso.','500_1000':'Entre 500 metros e 1 quilômetro do percurso.','gt_1000':'Fora das zonas exibidas no mapa.'};
  return <section className="mt-4 rounded-[22px] border border-[#dce4df] bg-white p-5"><h2 className="text-base font-semibold">Quantos CEPs estão em cada zona de distância?</h2><p className="mt-1 text-xs leading-5 text-[#77827e]">Distribuição dos pontos pela <strong>distância ao percurso</strong> provisório. Total: <strong>{total?total.toLocaleString('pt-BR'):'…'} pontos</strong>.</p>
    <div className="mt-5 space-y-4">{ordered.map((item)=>{const count=Number(item.point_count);const share=total?count/total*100:0;return <div key={item.code}><div className="mb-1.5 flex flex-wrap items-end justify-between gap-2"><div><p className="text-xs font-semibold text-[#35413d]">{labels[item.code]??item.label}</p><p className="text-[10px] text-[#7d8884]">{explanations[item.code]}</p></div><p className="text-xs text-[#53615b]"><strong>{count.toLocaleString('pt-BR')}</strong> pontos · <strong>{formatPercentPrecise(share)}</strong></p></div><div className="h-3 overflow-hidden rounded-full bg-[#edf1ee]"><div className="h-full min-w-[3px] rounded-full bg-[#d97835]" style={{width:`${share}%`}}/></div></div>;})}</div>
    <div className="mt-5 rounded-2xl bg-[#f3f6f4] p-4 text-xs leading-5 text-[#5f6c67]"><h3 className="font-semibold text-[#35413d]">Como interpretar?</h3><p className="mt-1">Essas faixas mostram a distância entre cada CEP georreferenciado e o percurso do metrô utilizado atualmente na análise. Por exemplo, um ponto na faixa de 100–250 m está entre 100 e 250 metros do traçado.</p><p className="mt-2 font-medium text-[#6d5a24]">As faixas são exploratórias. Elas não indicam, sozinhas, valorização ou desvalorização imobiliária.</p></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{cumulative.map((item)=><article key={item.label} className="rounded-2xl border border-[#e0e6e2] bg-[#fafbfa] p-4"><p className="text-[11px] font-medium text-[#68746f]">{item.label}</p><p className="mt-2 text-xl font-semibold tracking-[-.035em]">{item.count.toLocaleString('pt-BR')}</p><p className="mt-1 text-xs font-semibold text-[#176b52]">{formatPercentPrecise(total?item.count/total*100:0)} do total</p></article>)}</div>
  </section>;
}
function meters(value:number){return Math.round(value).toLocaleString('pt-BR');}
function compactMeters(value:number){return value>=1000?`${(value/1000).toLocaleString('pt-BR',{maximumFractionDigits:1})}k`:String(Math.round(value));}
function humanDistance(value:number){return value>=1000?`${(value/1000).toLocaleString('pt-BR',{maximumFractionDigits:2})} km`:`${value.toLocaleString('pt-BR')} m`;}
function kilometers(value:number){return `${(value/1000).toLocaleString('pt-BR',{maximumFractionDigits:2})} km`;}
function percentage(value:number,total:number){return total?`${(value/total*100).toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`:'—';}
function formatPercent(value:number){return `${value.toLocaleString('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1})}%`;}
function formatPercentPrecise(value:number){return `${value.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2})}%`;}
function atThreshold(data:EcdfPoint[],threshold:number){const exact=data.find((item)=>item.threshold_m===threshold);return exact?Number(exact.cumulative_percentage):undefined;}
function friendlyResult(code:string){return code==='dl01'?'Correspondência determinística de logradouro — maior precisão':code==='pl01'?'Correspondência probabilística de logradouro':code==='outros'?'Outros códigos':`Correspondência determinística de logradouro — classe ${code.slice(-2)}`;}
function summarizeResultTypes(data:GeocodingQualitySummary[]){const rows=data.filter((item)=>item.dimension==='result_type');const known=['dl01','dl03','dl04','pl01'];const result=known.map((code)=>({dimension:'result_type' as const,group_value:code,n:rows.find((item)=>item.group_value===code)?.n??0})).filter((item)=>item.n>0);const other=rows.filter((item)=>!known.includes(item.group_value)).reduce((sum,item)=>sum+item.n,0);return other?[...result,{dimension:'result_type' as const,group_value:'outros',n:other}]:result;}
function mergeEcdf(station:EcdfPoint[],track:EcdfPoint[]){const s=new Map(station.map((item)=>[item.threshold_m,Number(item.cumulative_percentage)]));const t=new Map(track.map((item)=>[item.threshold_m,Number(item.cumulative_percentage)]));const thresholds=[...new Set([...s.keys(),...t.keys()])].sort((a,b)=>a-b);let sv=0,tv=0;return thresholds.map((threshold_m)=>{sv=s.get(threshold_m)??sv;tv=t.get(threshold_m)??tv;return{threshold_m,station:sv,track:tv};});}
